# skip boilerplate check
---
# start of document (---) avoids errors if the file only contains comments

# yaml-language-server: $schema=../../../../schemas/vpc.schema.json

project_id: $project_ids:net-prod-0
name: prod-0
delete_default_routes_on_create: true
mtu: 1500
nat_config:
  nat-primary:
    region: $locations:primary
ncc_config:
  hub: $ncc_hubs:hub
  group: $ncc_groups:hub/default
psa_configs:
  - ranges:
      psa: 10.72.224.0/24
    export_routes: true
    import_routes: true
    peered_domains:
      - "test."
routes:
  default:
    dest_range: 0.0.0.0/0
    next_hop_type: "gateway"
    next_hop: "default-internet-gateway"
subnets_proxy_only:
  - ip_cidr_range: 10.72.240.0/24
    region: $locations:primary
    name: primary-region-proxy-only
    active: true
