# skip boilerplate check
---
# start of document (---) avoids errors if the file only contains comments

# yaml-language-server: $schema=../../../../schemas/vpc.schema.json

project_id: $project_ids:net-dev-0
name: dev-0
delete_default_routes_on_create: true
mtu: 1500
nat_config:
  nat-primary:
    region: $locations:primary
ncc_config:
  hub: $ncc_hubs:hub
  group: $ncc_groups:hub/default
routes:
  default:
    dest_range: 0.0.0.0/0
    next_hop_type: "gateway"
    next_hop: "default-internet-gateway"
