# skip boilerplate check
---
# start of document (---) avoids errors if the file only contains comments

# yaml-language-server: $schema=../../../../schemas/vpc.schema.json

project_id: $project_ids:net-core-0
name: hub-0
delete_default_routes_on_create: true
nat_config:
  nat-ew8:
    region: $locations:primary
peering_config:
  to-prod:
    peer_network: $networks:prod
  to-dev:
    peer_network: $networks:dev
routers:
  vpn-router:
    region: $locations:primary
    asn: 64514
    # Uncomment to enable custom route advertisement. (see https://docs.cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip)
    # custom_advertise:
    #   all_subnets: true
    #   ip_ranges:
    #     # Uncomment to advertise the Cloud DNS query source address range. (see https://docs.cloud.google.com/dns/docs/server-policies-overview#altns-targets:~:text=0/19-,Type%202%20name%20server,-An%20IP%20address)
    #     "35.199.192.0/19": "cloud-dns-resolver"
    #     # Uncomment to advertise the Private Google Access routes. (see https://docs.cloud.google.com/vpc/docs/private-google-access-hybrid)
    #     "199.36.153.8/30": "private-googleapis-com-ipv4"
    #     "2600:2d00:0002:2000::/56": "private-googleapis-com-ipv6"
    #     # Uncomment to advertise the Private Google Access routes that support VPC Service Controls. (see https://docs.cloud.google.com/vpc/docs/private-google-access-hybrid)
    #     "199.36.153.4/30": "restricted-googleapis-com-ipv4"
    #     "2600:2d00:0002:1000::/56": "restricted-googleapis-com-ipv6"
routes:
  default:
    dest_range: 0.0.0.0/0
    next_hop_type: "gateway"
    next_hop: "default-internet-gateway"
# dns_policy:
#   logging: true
