# skip boilerplate check
---
# start of document (---) avoids errors if the file only contains comments

# yaml-language-server: $schema=../../../../schemas/vpc.schema.json

project_id: $project_ids:net-core-0
name: hub-0
delete_default_routes_on_create: true
routers:
  vpn-router:
    region: $locations:primary
    asn: 64514
routes:
  default:
    dest_range: 0.0.0.0/0
    next_hop_type: "gateway"
    next_hop: "default-internet-gateway"
