# skip boilerplate check
---
# start of document (---) avoids errors if the file only contains comments

# yaml-language-server: $schema=../../../../schemas/vpc.schema.json

project_id: $project_ids:net-core-0
name: hub
delete_default_routes_on_create: false
nat_config:
  nat-ew8:
    region: europe-west8
routers:
  vpn-router:
    region: europe-west8
    asn: 64514
    custom_advertise:
      ip_ranges:
        "10.0.0.0/8": "rfc1918-10"
        "172.16.0.0/12": "rfc1918-172"
        "192.168.0.0/16": "rfc1918-192"
routes:
  gateway:
    dest_range: "8.8.8.8/32"
    priority: 100
    next_hop_type: "gateway"
    next_hop: "default-internet-gateway"
