# skip boilerplate check
---
# start of document (---) avoids errors if the file only contains comments

# yaml-language-server: $schema=../../../../schemas/vpc.schema.json

project_id: $project_ids:net-dev-0
name: dev-0
delete_default_routes_on_create: true
mtu: 1500
nat_config:
  nat-ew8:
    region: $locations:primary
peering_config:
  to-hub:
    peer_network: $networks:hub
routes:
  default:
    dest_range: 0.0.0.0/0
    next_hop_type: "gateway"
    next_hop: "default-internet-gateway"
